<?php


/**
 * Implements hook_menu().
 */
function islandora_usage_stats_callbacks_menu() {
  $items = array();

  $items['islandora_usage_stats_callbacks/object_stats/%'] = array (
    'page callback' => 'islandora_usage_stats_callbacks_get_object_stats',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );

  $items['admin/islandora/tools/islandora_usage_stats_callbacks'] = array(
    'title' => 'Islandora Usage Stats Callbacks Settings',
    'description' => 'Change behavior of Islandora Usage Stats Callbacks.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_usage_stats_callbacks_admin_form'),
    'access arguments' => array('manage usage stats callbacks'),
    'file' => 'includes/admin.form.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_usage_stats_callbacks_permission() {
  return array(
    'manage usage stats callbacks' => array(
      'title' => 'Manage usage stats callbacks configuration',
      'description' => 'Manage the configuration of the Usage Stats Callbacks module',
    ),
  );
}


/**
 * Callback functions
 */
function islandora_usage_stats_callbacks_get_object_stats($pid) {
  $report = array();
  $ids = islandora_usage_stats_callbacks_get_object_ids($pid);
  $legacy_stats = islandora_usage_stats_callbacks_get_legacy_stats($pid);
  $report['pid'] = $ids['pid'];
  $report['cmodel'] = $ids['cmodel'];
  $report['legacy-views'] = $legacy_stats['views'];
  $report['legacy-downloads'] = $legacy_stats['downloads'];
  $report['views'] = islandora_usage_stats_callbacks_get_object_views($ids);
  $report['downloads'] = isset($ids['dsid']) ? islandora_usage_stats_callbacks_get_object_downloads($ids) : FALSE;
  echo json_encode($report);
  drupal_exit();
}

/**
 * Legacy stats reader
 */
function islandora_usage_stats_callbacks_get_legacy_stats($pid) {
  $legacy_stats = array();
  //$legacy_stats_file_loc = $_SERVER['DOCUMENT_ROOT'] . "/" . drupal_get_path('module', 'islandora_usage_stats_callbacks') . "/legacy-stats.csv";
  $legacy_stats_file_loc = variable_get('islandora_usage_stats_callbacks_legacy_stats_file_location', ''); 
  if (($legacy_stats_file_loc != '') && file_exists($legacy_stats_file_loc)) {
    $legacy_data = array();
    $legacy_data_csv = array_map('str_getcsv', file($legacy_stats_file_loc));
    foreach ($legacy_data_csv as $row) {
      $legacy_pid = $row[0];
      $legacy_views = $row[1];
      $legacy_downloads = $row[2];
      $legacy_data[$legacy_pid] = array("legacy-views" => $legacy_views, "legacy-downloads" => $legacy_downloads);
    }
    if (array_key_exists($pid, $legacy_data)) {
      $legacy_stats['views'] = intval($legacy_data[$pid]['legacy-views']);
      $legacy_stats['downloads'] = intval($legacy_data[$pid]['legacy-downloads']); 
    }
    else {
      $legacy_stats['views'] = 0;
      $legacy_stats['downloads'] = 0;
    }
  }
  else {
    $legacy_stats['views'] = 0;
    $legacy_stats['downloads'] = 0;
  }
  return $legacy_stats;
}

/**
 * DB parsing helper functions
 */
function islandora_usage_stats_callbacks_get_object_ids($pid) {

  # Check PID string format before proceeding 
  module_load_include('inc', 'islandora', 'includes/utilities');
  if (!islandora_is_valid_pid($pid)) {
    echo json_encode(array('error' => "PID '${pid}' is not a valid PID string")); 
    drupal_exit();
  }

  $ids = array();
  $ids['pid'] = $pid;
  $ids['cmodel'] = islandora_object_load($pid)->models[0];
  $cmodel_dsids = array('ir:citationCModel' => 'PDF',
                        'ir:thesisCModel' => 'PDF',
                        'islandora:sp_pdf' => 'OBJ',
                        'islandora:sp_basic_image' => 'OBJ',
                        'islandora:sp_large_image_cmodel' => 'OBJ',
                        'islandora:collectionCModel' => FALSE,
                        'islandora:compoundCModel' => FALSE,
                        'islandora:newspaperCModel' => FALSE,
                        'islandora:newspaperIssueCModel' => FALSE,
                        'islandora:newspaperPageCModel' => 'OBJ',
                        'islandora:sp-audioCModel' => 'OBJ',
                        'islandora:sp_videoCModel' => 'OBJ',
                        'islandora:sp_web_archive' => 'OBJ',
                        'islandora:sp_disk_image' => 'OBJ',
                        'islandora:bookCModel' => FALSE,
                        'islandora:pageCModel' => 'OBJ');
  if ($ids['cmodel'] == '') {
    echo json_encode(array('error' => "PID '${ids['pid']}' does not exist")); 
    drupal_exit();
  }
  elseif (!in_array($ids['cmodel'], array_keys($cmodel_dsids))) {
    echo json_encode(array('error' => "unsupported content model '${ids['cmodel']}'")); 
    drupal_exit();
  }
  $ids['dsid'] = $cmodel_dsids[$ids['cmodel']];
  $result = db_select('islandora_usage_stats_objects')
    ->fields('islandora_usage_stats_objects', array('id'))
    ->condition('pid', $pid)
    ->execute();
  $record = $result->fetchAssoc();
  $ids['usid'] = $record['id'];
  if ($ids['usid'] == '') {
    echo json_encode(array('pid' => $ids['pid'], 'cmodel' => $ids['cmodel'], 'views' => array(), 'downloads' => array()));
    drupal_exit();
  } 
  return $ids;
}

function islandora_usage_stats_callbacks_get_object_views($ids) {
  $result = db_select('islandora_usage_stats_object_access_log')
    # IP address temporarily disabled for security reasons
    #->fields('islandora_usage_stats_object_access_log', array('time', 'ip'))
    ->fields('islandora_usage_stats_object_access_log', array('time'))
    ->condition('pid_id', $ids['usid'])
    ->execute();
  $record = $result->fetchAll();
  return $record;
}

function islandora_usage_stats_callbacks_get_object_downloads($ids) {
  $ds_check_query = db_select('islandora_usage_stats_datastreams')
    ->fields('islandora_usage_stats_datastreams', array('id'))
    ->condition('pid_id', $ids['usid'])
    ->condition('dsid', $ids['dsid'])
    ->execute();
  $ds_check_result = $ds_check_query->fetchAssoc();
  if ($ds_check_result['id']) {
    $result = db_select('islandora_usage_stats_object_ds_access_log')
      # IP address temporarily disabled for security reasons
      #->fields('islandora_usage_stats_object_ds_access_log', array('time', 'ip'))
      ->fields('islandora_usage_stats_object_ds_access_log', array('time'))
      ->condition('ds_id', $ds_check_result['id'])
      ->execute();
    $record = $result->fetchAll();
    return $record;
  }
  else {
    return array();
  }
}
