<?php

/**
 * Implements hook_menu().
 */
function islandora_usage_stats_callbacks_menu() {
  $menu['islandora_usage_stats_callbacks/object_stats/%'] = array (
    'page callback' => 'islandora_usage_stats_callbacks_get_object_stats',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );
  return $menu;
}


/**
 * Callback functions
 */
function islandora_usage_stats_callbacks_get_object_stats($pid) {
  $report = array();
  $ids = islandora_usage_stats_callbacks_get_object_ids($pid);
  $report['pid'] = $ids['pid'];
  $report['cmodel'] = $ids['cmodel'];
  $report['usid'] = $ids['usid'];
  $report['views'] = islandora_usage_stats_callbacks_get_object_views($ids);
  $report['downloads'] = islandora_usage_stats_callbacks_get_object_downloads($ids);
  echo json_encode($report);
  drupal_exit();
}


/**
 * DB parsing helper functions
 */
function islandora_usage_stats_callbacks_get_object_ids($pid) {
  $ids = array();
  $ids['pid'] = $pid;
  $ids['cmodel'] = islandora_object_load($pid)->models[0];
  $cmodel_dsids = array('ir:citationCModel' => 'PDF', 
                        'ir:thesisCModel' => 'PDF', 
                        'islandora:sp_pdf' => 'OBJ');
  if ($ids['cmodel'] == '') {
    echo json_encode(array('error' => "invalid PID '${ids['pid']}'")); 
    drupal_exit();
  }
  elseif (!in_array($ids['cmodel'], array_keys($cmodel_dsids))) {
    echo json_encode(array('error' => "unsupported content model '${ids['cmodel']}'")); 
    drupal_exit();
  }
  $ids['dsid'] = $cmodel_dsids[$ids['cmodel']];
  $result = db_select('islandora_usage_stats_objects')
    ->fields('islandora_usage_stats_objects', array('id'))
    ->condition('pid', $pid)
    ->execute();
  $record = $result->fetchAssoc();
  $ids['usid'] = $record['id'];
  if ($ids['usid'] == '') {
    echo json_encode(array('pid' => $ids['pid'], 'cmodel' => $ids['cmodel'], 'views' => array(), 'downloads' => array()));
    drupal_exit();
  } 
  return $ids;
}

function islandora_usage_stats_callbacks_get_object_views($ids) {
  $result = db_select('islandora_usage_stats_object_access_log')
    ->fields('islandora_usage_stats_object_access_log', array('time', 'ip'))
    ->condition('pid_id', $ids['usid'])
    ->execute();
  $record = $result->fetchAll();
  return $record;
}

function islandora_usage_stats_callbacks_get_object_downloads($ids) {
  $ds_check_query = db_select('islandora_usage_stats_datastreams')
    ->fields('islandora_usage_stats_datastreams', array('id'))
    ->condition('pid_id', $ids['usid'])
    ->condition('dsid', $ids['dsid'])
    ->execute();
  $ds_check_result = $ds_check_query->fetchAssoc();
  if ($ds_check_result['id']) {
    $result = db_select('islandora_usage_stats_object_ds_access_log')
      ->fields('islandora_usage_stats_object_ds_access_log', array('time', 'ip'))
      ->condition('ds_id', $ds_check_result['id'])
      ->execute();
    $record = $result->fetchAll();
    return $record;
  }
  else {
    return array();
  }
}
